In [1]:
from utils.data_depth import DepthDataset
from utils.plot import plot_3d_pointcloud

In [2]:
dataset = DepthDataset(partition='train', 
                       outputs=['depth', 'edge_label', 'edge_index'],
                       pc_mean=0.5,          # Hace que la media de valores de profundidad (Z) sea 0.5 (mejora el resultado de regresión con Sigmoid)
                       repeat=1,             # Repite los elementos del dataset (sólo lo uso cuando overfitteo a un modelo y quiero usar batch_size > 1)
                       shuffle_pixels=False, # Mezcla aleatoriamente los pixeles dentro de cada modelo (no está implementado para edge_label y edge_index)
                       preload=True)         # Almacena el dataset en RAM

In [3]:
pixels, depth, edge_label, edge_index = dataset[0]
plot_3d_pointcloud(dataset.denormalize(pixels), depth, dataset.im_shape)

C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\_asarray.py:171: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return array(a, dtype, copy=False, order=order, subok=True)


Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0034360…

In [10]:
print('pixels shape:', pixels.shape, '-> (XY, N)')
print('depth shape:', depth.shape, '-> (Z, N)')
print('edge_label shape:', edge_label.shape, '-> (N, k)')
print('edge_index shape:', edge_index.shape, '-> (2, N*k)')

pixels shape: (2, 2000) -> (XY, N)
depth shape: (2000,) -> (Z, N)
edge_label shape: (2000, 20) -> (N, k)
edge_index shape: (2, 40000) -> (2, N*k)


In [11]:
pixels

array([[ 0.4       , -0.0037037 ,  0.31851852, ...,  0.37407407,
        -0.01851852,  0.54814816],
       [ 0.17037037,  0.25925925,  0.25925925, ...,  0.15925926,
        -0.26666668,  0.31111112]], dtype=float32)

In [12]:
depth

array([0.6694117 , 0.43411762, 0.49294114, ..., 0.6694117 , 0.512549  ,
       0.51647055], dtype=float32)

In [13]:
edge_label

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [15]:
edge_label.sum()

373

In [14]:
edge_index

array([[   0,    0,    0, ..., 1999, 1999, 1999],
       [ 164,  201,  233, ..., 1661, 1728, 1781]], dtype=int64)